<a href="https://colab.research.google.com/github/kanakabs/Online-Workshop-Applications-of-Python-programming/blob/master/Day_3_Session_2_Pandas_and_numpy_Exercise_Questions_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Write a Pandas program to create and display a one-dimensional array using series  containing  event numbers upto 10000
#tip : use List Comprehension
#ds = pd.Series([0,2, 4, 6, 8..... 10000]) 
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


In [2]:

#Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and  after convertion print its type 
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)


0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


In [3]:

#Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [4]:

#4.Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
#Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [5]:
#5.Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [6]:

#6.Write a Pandas program to convert a given Series to an array.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


In [7]:

#7.Write a Pandas program to sort a given Series.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)


Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


In [8]:
#8.Write a Pandas program to create a subsets of a given series based on value and condition.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5

import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


In [9]:
#9.Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


In [10]:

#10.Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [ ]:
#11.Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])


!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials


auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'1hzxXR0uL-JosrCjV6JNn4g9FRMttT5rP'}) # replace the id with id of file you want to access
downloaded.GetContentFile('movies_metadata.csv') 

import pandas as pd
xyz = pd.read_csv('movies_metadata.csv') 
print(xyz.head(1))



In [ ]:
#12.Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(movie_metadata.csv file).

import pandas as pd
df = pd.read_csv('movies_metadata.csv')
seventh_movie = df.iloc[3]
print("Details of the seventh movie:")
print(seventh_movie)


In [ ]:

#13.Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields

import pandas as pd
df = pd.read_csv('movies_metadata.csv')
result = df[['title', 'genres']]
print("Details of title and genres:")
print(result)

In [ ]:

#14.Write a Pandas program to sort the DataFrame based on country and language from dataset of movie_metadata.csv

import pandas as pd
df = pd.read_csv('movies_metadata.csv')
# Create a smaller dataframe
small_df = df[['title', 'release_date', 'budget', 'revenue', 'runtime']]
result = small_df.sort_values('release_date')
print("DataFrame based on country and language.")
print(result)


In [15]:

#15.Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 

Original Array:
[[0.09566479 0.40479496 0.05699071 0.49161983]
 [0.95080591 0.92090495 0.65805135 0.57907464]
 [0.62348646 0.93618568 0.57632126 0.62035946]
 [0.81554782 0.3383092  0.18384821 0.77027923]]


In [16]:

#16.Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.00392012 0.72527033 0.71078176 0.58429335 0.15202381 0.83302592
  0.15986208 0.42498181 0.47954571 0.80796991]
 [0.26269435 0.22392037 0.62379439 0.07706657 0.5808097  0.50382863
  0.07942869 0.28940602 0.96005002 0.1773168 ]
 [0.31977141 0.76676896 0.57905058 0.14938926 0.45822008 0.08699465
  0.31248103 0.42878084 0.115996   0.98554257]
 [0.87008141 0.71806041 0.27730561 0.70334438 0.82445638 0.58987535
  0.3796713  0.90903051 0.80311715 0.97810477]
 [0.42936588 0.0101653  0.9176917  0.15042527 0.52734977 0.07907766
  0.08158001 0.96421425 0.22618019 0.07415608]
 [0.00704057 0.53390854 0.35943827 0.67576634 0.89681938 0.01664746
  0.11835935 0.75563037 0.20222478 0.5181283 ]
 [0.66978211 0.83047364 0.38643345 0.33844524 0.93551953 0.25355478
  0.55315855 0.87611879 0.84109376 0.21877897]
 [0.32838104 0.33667753 0.35093528 0.27648866 0.57828258 0.70099889
  0.91951252 0.95574959 0.91630575 0.04101913]
 [0.3727367  0.13462263 0.41531547 0.14854555 0.99064051 0.01998

In [17]:
#17.Write a NumPy program to generate 8 random integers between 100 and 300

import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)


[147 152 137 132 181 165 219 139]


In [18]:
#18.Write a NumPy program to create a random integer nos of size 20 and sort it

import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.95139396 0.46827392 0.08666022 0.13486833 0.90722609 0.22120233
 0.32783759 0.59179384 0.78367686 0.08922535 0.97577066 0.38944129
 0.95959897 0.22537912 0.6081764  0.56155033 0.05388822 0.94088341
 0.19055426 0.62717132]
Sorted array:
[0.05388822 0.08666022 0.08922535 0.13486833 0.19055426 0.22120233
 0.22537912 0.32783759 0.38944129 0.46827392 0.56155033 0.59179384
 0.6081764  0.62717132 0.78367686 0.90722609 0.94088341 0.95139396
 0.95959897 0.97577066]
